#!/bin/sh
# A dmenu binary prompt script.
# Gives a dmenu prompt labeled with $1 to perform command $2.
# For example:
# `./prompt "Do you want to shutdown?" "shutdown -h now"`

choice=$(echo -e "No\nYes" | dmenu -i -p "$1" -nb darkred -sb red -sf white -nf gray -fn mono)

cmd=$2

[ -z $1 ] && echo missing prompt text && exit 1
if [ -z "${cmd}" ]; then
    [  $choice == "Yes" ] && exit 0
    [  $choice == "No" ] && exit 1
else
    [  $choice == "No" ] && exit 0
    [  $choice == "Yes" ] && ${cmd}
fi
